hydra:
  job:
    chdir: False
train:
  seq: 'cook_spinach_2'
  exp: 'dust3r'
  resize: True
  resize_size: 512
dust3r:
  device: 'cuda'
  batch_size: 1
  schedule: 'cosine'
  scene_graph: 'swin-5' # Use complete if you have a lot of VRAM
  scene_scale: 10.0 # For some reason the scene is too small by default and the rasterizer ends up culling a good chunk
  lr: 0.01
  niter: 500
  model_name: ./dust3r/checkpoints/DUSt3R_ViTLarge_BaseDecoder_512_dpt.pth

sparsify:
  enabled: False
  num_samples: 300000 # Not sure

data:
  path: './data/cook_spinach_2'
  priors: './data/cook_spinach_2/priors.npz'
  force_extract: False