hydra:
  job:
    chdir: False
train:
  seq: 'cook_spinach'
  exp: 'dust3r'
dust3r:
  device: 'cuda'
  batch_size: 1
  schedule: 'cosine'
  scene_graph: 'swin-5' # Use complete if you have a lot of VRAM
  lr: 0.01
  niter: 300
  model_name: ./dust3r/checkpoints/DUSt3R_ViTLarge_BaseDecoder_512_dpt.pth

sparsify:
  enabled: True
  num_samples: 500000 # Not sure

data:
  path: './data/cook_spinach'
  priors: './data/cook_spinach/priors.npz'
  force_extract: False